# Services are needed to connect to Deployments
apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  type: NodePort # this allows external access
  selector:
    app: config # should match metadata.labels.app in the appropriate Deployment
  ports:
  - protocol: TCP
    port: 80 # port exposed by this Service within the cluster
    targetPort: 80 # containerPort on the Deployment below
    nodePort: 30060 # external port on the minikube node that this will be accessible from - between (30000-32767)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
spec:
  selector:
    matchLabels:
      app: config
  replicas: 1
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - name: config
        image: govukverify/config
        ports:
        - containerPort: 80
