# Services are needed to connect to Deployments
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort # this allows external access
  selector:
    app: frontend # should match metadata.labels.app in the appropriate Deployment
  ports:
  - protocol: TCP
    port: 30020 # port exposed by this Service within the cluster
    targetPort: 80 # containerPort on the Deployment below
    nodePort: 30020 # external port on the minikube node that this will be accessible from - between (30000-32767)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: govukverify/frontend
        ports:
        - containerPort: 80
        env:
        - name: LOG_PATH
          value: "logs"
