# Services are needed to connect to Deployments
apiVersion: v1
kind: Service
metadata:
  name: saml-engine-service
spec:
  type: NodePort # this allows external access
  selector:
    app: saml-engine # should match metadata.labels.app in the appropriate Deployment
  ports:
  - protocol: TCP
    port: 80 # port exposed by this Service within the cluster
    targetPort: 80 # containerPort on the Deployment below
    nodePort: 30100 # external port on the minikube node that this will be accessible from - between (30000-32767)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saml-engine-deployment
spec:
  selector:
    matchLabels:
      app: saml-engine
  replicas: 1
  template:
    metadata:
      labels:
        app: saml-engine
    spec:
      # this is a pretty gross hack to point localhost to the gateway/host ip address
      # so that the app thinks the metadata has been resolved from the "localhost" in the entityId
      hostAliases:
        - ip: "192.168.99.1"
          hostnames:
          - "localhost"
      containers:
      - name: saml-engine
        image: govukverify/saml-engine
        ports:
        - containerPort: 80
        env:
        - name: METADATA_ENTITY_ID
          value: "https://dev-hub.local"
        - name: FRONTEND_URL # external url
          value: "http://192.168.99.100:30020"
        - name: CONFIG_URL
          value: "http://config-service"
        - name: METADATA_URL
          value: "http://localhost:55500/dev.xml"
        - name: EIDAS_ENABLED
          value: "true"
        - name: HUB_CONNECTOR_ENTITY_ID
          value: "http://localhost:55500/dev-connector.xml"
        - name: TRUST_ANCHOR_URL
          value: "http://localhost:55500/trust-anchor"
        - name: METADATA_SOURCE_URI
          value: "http://localhost:55500/aggregator"
