# Services are needed to connect to Deployments
apiVersion: v1
kind: Service
metadata:
  name: stub-event-sink-service
spec:
  type: NodePort # this allows external access
  selector:
    app: stub-event-sink # should match metadata.labels.app in the appropriate Deployment
  ports:
  - protocol: TCP
    port: 80 # port exposed by this Service within the cluster
    targetPort: 80 # containerPort on the Deployment below
    nodePort: 30050 # external port on the minikube node that this will be accessible from - between (30000-32767)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stub-event-sink-deployment
spec:
  selector:
    matchLabels:
      app: stub-event-sink
  replicas: 1
  template:
    metadata:
      labels:
        app: stub-event-sink
    spec:
      containers:
      - name: stub-event-sink
        image: govukverify/stub-event-sink
        ports:
        - containerPort: 80
